# Generated by Django 2.2.8 on 2019-12-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='childrens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=30)),
                ('childs', models.ManyToManyField(to='relationshipsapp.childrens')),
            ],
        ),
        migrations.CreateModel(
            name='game_playing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_play', models.CharField(max_length=60)),
                ('game_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationshipsapp.childrens')),
            ],
        ),
    ]
